### ISSUE TITLE
Balance and Credit Details are missing available Products that Plaid offers

### ISSUE THREAD

**Issue by DeRiderConsultingServices** [viceroypenguin/Going.Plaid.NET#19]
https://github.com/viceroypenguin/Going.Plaid.NET/blob/master/src/Plaid/Entity/Product.cs
is missing Balance and CreditDetails as available enum options on Products that you can either a) search for/interact with or b) that various objects such as Institution will return as valid values. 

Since your API model bounces between strings and enums this is tripping me up. I'm not sure if this is intentional or if you want me to create a PR for this. 

https://plaid.com/docs/api/institutions/
Filter the Institutions based on which products they support.
Possible values: assets, auth, balance, identity, investments, liabilities, payment_initiation, transactions, credit_details, income

**Comment by viceroypenguin** [comment]
I created a PR, please take a look. The documentation is not clear on what `credit_details` actually refer to, since there is no product called "Credit Details", and most liability information is under the Liabilities product. If you have a better idea, please feel free to let me know or update the PR yourself. I'll do a new release as soon as I can.

**Comment by viceroypenguin** [comment]
v2.2.0 released with this change. Hope this helps!

**Comment by DeRiderConsultingServices** [comment]
Thanks for the fast turn-around on this :) Kudos. Great library too. Saving me some time in a Plaid integration for a client.
